### ISSUE TITLE
refactor: create react app

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/algorithms#60]
Create React App and put these two directories "data structures" and "algorithms" inside of it.

The idea is to have the react app which I can later deploy with Netlify to test my data structures & algorithms.

**Comment by umesh-9** [comment]
@anicmarko9  can i take this issue ... and please let me know what kind of stuff do for react app or simply create-react-app and add the two directories

**Comment by anicmarko9** [comment]
Create React App with some home page. I need this to test my data structures and algorithms, so maybe just add a home page, that is going to be on route "/" with one JSX Element, probably <pre> </pre> or something similar.

**Comment by umesh-9** [comment]
ok i got the point. i am working on it
